#!/bin/bash
repoName=$1

while [ -z "$repoName" ]; do
    echo 'Provide a repository name'
    read -r -p 'Repository name: ' repoName
done

echo "# $repoName" >> README.md
git init
git add .
git commit -m "First Commit"

# Create the GitHub repository
curl -u felipecostacouto https://api.github.com/user/repos -d "{\"name\": \"$repoName\", \"private\": false}"

# Retrieve the repository URL
GIT_URL=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/felipecostacouto/"$repoName" | jq -r '.clone_url')

# Set up git and push
git branch -M main
git remote add origin "$GIT_URL"
git push -u origin main
